### ISSUE TITLE
Update CondNumber range to include 0

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/OpenDataStandards#11]
Please update CondNumber to start with 0. Quite a few clients use CondNumber = 0.

**Comment by MattDonovan82** [comment]
to confirm this would just be "[0,)" in the 'Valid Value Range' column?

**Comment by aiste-kalinauskaite** [comment]
yes, correct

**Comment by MattDonovan82** [comment]
Implemented into the .xslx and .csv files
