### ISSUE TITLE
Add Option to ContentsFloodVulnerability field

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OpenDataStandards#12]
ContentsFloodVulnerability currently has options:

0 = Unknown
1 = Low
2 = Medium
3 = High
4 = Very High

Request that an option 5 = No Susceptibility be added to support some flood models using this field.

**Comment by MattDonovan82** [comment]
this would suggest that the description should read "All contents are are water-resistant or protected"?

**Comment by MattDonovan82** [comment]
done
