### ISSUE TITLE
Updated to valid ranges

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/OpenDataStandards#13]
Please update these valid ranges:

FirstFloorHeight
GroundElevation
FloodDefenseHeight
BuildingHeight

All to have Valid range (column H) = [-999,)
Reason for the update: ranges set incorrectly in the initial version.

**Comment by MattDonovan82** [comment]
Done - implemented changes in .csv doc in 'schema' folder and OED data spec .xlsx in 'Docs' folder
