### ISSUE TITLE
Request for additional GeogScheme codes

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OpenDataStandards#15]
For our continued model development, we'd like to ask for some new entries into the list of permitted OED GeogScheme values.

Firstly, could **PCA (Postcode Area)** be added as a generic entry? For the spec's example postcode of "EC3A 5NR (UK)", the example for PCA would be "EC (UK)".

Secondly, could we expand the current JBA1 code to be six codes, **JBA1** through **JBA6**? Like the GADMx or CRSLx codes, JBA1 is the coarsest (top) level administrative boundary, and JBA6 the finest level. These would be implemented on a per-model basis, with values documented as required.

Could you let me know once you're happy to accept these (even if not yet in the spec), so I can pass that on to our data developers? We'd need them added to the OED spec by the end of the year (I'm sure you'll make an update long before then, though).

**Comment by MattDonovan82** [comment]
I will add these requests to the data spec as their should not be a problem accepting these changes.

**Comment by jones-matt** [comment]
The JBA1..6 changes make sense.
Instead of a new PCA Geogscheme, could the AreaCode field be used instead?  For GB this already used the Postcode Area values.

**Comment by MattDonovan82** [comment]
@DanielFEvans Just following up on this. As per Matt J comment could the AreaCode field be used?

**Comment by MattDonovan82** [comment]
@DanielFEvans have you managed to look at the Area Code field as per Matt J's comment?

**Comment by DanielFEvans** [comment]
It had made it as far as one of our cat modellers' to-do lists, but they've since had both sick leave and holiday, and aren't back until Monday. I apologise for the delay!

**Comment by DanielFEvans** [comment]
Ah, no, my apologies - I'd missed a reply deep in my inbox.

We're happy to use AreaCode for UK Postcode Areas.

**Comment by MattDonovan82** [comment]
thanks.
