### ISSUE TITLE
Request for additional industrial occupancies/ facilities

### ISSUE THREAD

**Issue by delioma** [OasisLMF/OpenDataStandards#16]
Dear Matthew
We would be grateful if you please included the following industrial occupancies and assets in the industrial facilities model (please find attatched)

with best regards
Delioma Oramas-Dorta
Guy Carpenter

[Industrial Assets OED request.xlsx](https://github.com/OasisLMF/OpenDataStandards/files/5363978/Industrial.Assets.OED.request.xlsx)

**Comment by MattDonovan82** [comment]
@delioma have you looked through the current industrial occupancy types? These can be viewed in the data spec in the doc folder or occupancy_values.csv in the schema folder https://github.com/OasisLMF/OpenDataStandards/blob/master/OpenExposureData/Schema/OED_Occupancy_Values.csv

**Comment by MattDonovan82** [comment]
@delioma as per your last email, please let me know the latest on this and whether this issue can be closed for now? thanks.

**Comment by MattDonovan82** [comment]
Hi @deliomaI. I will close this for now and it can be re-opened if necessary.
