### ISSUE TITLE
Link to DOI:10.1002/9781118906057 broken in OpenExposureData/Docs/OpenExposureData_Doc.pdf

### ISSUE THREAD

**Issue by pslh** [OasisLMF/OpenDataStandards#17]
If I open OpenExposureData/Docs/OpenExposureData_Doc.pdf in Acrobat Reader and clink on the link to the onlinelibrary.wiley.com found in the Resources section on page 56, I am presented with an error page.  If I copy/paste the link, then it works correctly.  It would appear that the final '7' char of the link is missing (perhaps due to a newline?)

The problematic link is:
[https://onlinelibrary.wiley.com/doi/book/10.1002/978111890605](https://onlinelibrary.wiley.com/doi/book/10.1002/978111890605)

The correct link is:
[https://onlinelibrary.wiley.com/doi/book/10.1002/9781118906057](https://onlinelibrary.wiley.com/doi/book/10.1002/9781118906057)

**Comment by MattDonovan82** [comment]
thanks - will update the link so the end is not on a new line
