### ISSUE TITLE
OED updates

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/OpenDataStandards#18]
Please update Valid Ranges (column H in 'OED Input Fields) - highlighted in orange:

StepNumber | [1,10]
Longitude | [-180,180]
YearBuilt | [0,)
NumberOfStoreys | [0,)
CondNumber | [0,)
BIWaitingPeriod | [0,)
YearUpgraded | [0,)
SurgeLeakage | [-999,-999], [0,1]
PercentSprinklered | [-999,-999], [0,1]
RoofYearBuilt | [0,)
BasementLevelCount | [0,5]
BaseFloodElevation | [-999,-999], [0,1]
CustomFloodSOP | [0,10000]
InuringPriority | [0,)
Reinstatement | [0,)

Please check that these have Valid Range = [-999,) for headers - highlighted in yellow:

FirstFloorHeight
GroundElevation
FloodDefenseHeight
BuildingHeight

Please add into 'Financial Code Values' tab TriggerType - highlighted in orange:

Financial Term | Code | Definition | Notes
TriggerType | 0 | Amount | For limits, 0 = unlimited
TriggerType | 1 | % of loss | Values <= 1 only
TriggerType | 2 | % of TIV | Values <= 1 only

UPDATED FILE (on 11 Nov):
[Open Exposure Data Spec_v1.1.2_develop_0909.xlsx](https://github.com/OasisLMF/OpenDataStandards/files/5523074/Open.Exposure.Data.Spec_v1.1.2_develop_0909.xlsx)

**Comment by benhayes21** [comment]
StepNumber | [1,10] - why is this limited to 10?

**Comment by benhayes21** [comment]
InuringPriority | [0,) support zero?

**Comment by aiste-kalinauskaite** [comment]
Good point on InuringPriority, let's have it **[1,)**
On StepNumber it's always been between 1 and 10 in the description, so I have added it to Valid range, so it's clearer. There is only one policy with 8 steps - that's the highest so far. It also matches AIR's maximum.

**Comment by aiste-kalinauskaite** [comment]
Removed 3 valid ranges, apparently it's too much and Data Type is enough. Updated file is added to the original ticket.

**Comment by MattDonovan82** [comment]
Added to data spec v1.1.3 in develop branch
