### ISSUE TITLE
Update ContentsFloodVuln

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/OpenDataStandards#19]
The file in #18 also contains this change. If it's not yet done, then ContentsFloodVuln should also have 5 as a valid value:

Category | Code | CodeDescription | Notes
ContentsFloodVuln | 5 | No Susceptibility | All of the contents are   water-resistant or protected

Ambiental use this.

**Comment by MattDonovan82** [comment]
Added to data spec v1.1.3 in develop branch
