### ISSUE TITLE
Update AreaCodes for Canada states

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/OpenDataStandards#2]
Current standard uses 2 digit codes for Canadian provinces. However, 2 letter codes are very well established. We have done a quick pole and there were no objections to the change. Could this be updated in the next OED release?

![image](https://user-images.githubusercontent.com/42062835/82230476-af2ba680-9923-11ea-80e5-8312b8f14183.png)

Category | CountryCode | AreaCode | AreaName | Resolution | Proposal
AreaCode | CA | 10 | Newfoundland | Province | NL
AreaCode | CA | 11 | Prince Edward Island | Province | PE
AreaCode | CA | 12 | Nova Scotia | Province | NS
AreaCode | CA | 13 | New Brunswick | Province | NB
AreaCode | CA | 24 | Quebec | Province | QC
AreaCode | CA | 35 | Ontario | Province | ON
AreaCode | CA | 46 | Manitoba | Province | MB
AreaCode | CA | 47 | Saskatchewan | Province | SK
AreaCode | CA | 48 | Alberta | Province | AB
AreaCode | CA | 59 | British Columbia | Province | BC
AreaCode | CA | 60 | Yukon | Province | YT
AreaCode | CA | 61 | North West Territories | Province | NT
AreaCode | CA | 62 | Nunavut | Province | NU

**Comment by MattDonovan82** [comment]
@aiste-kalinauskaite apologies for the delay in getting round to this. Is this just an update to the data spec?

we can make an update and release spec as v 1.1.3

**Comment by aiste-kalinauskaite** [comment]
Yes, it is a change in the spec. It would be great if it's released in v1.1.3

**Comment by MattDonovan82** [comment]
Added to data spec v1.1.3 in develop branch
