### ISSUE TITLE
Add flag for Condition Type to handle Policy Restrictions

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OpenDataStandards#20]
The main types of special conditions that we see are 1) sublimits, where a deductible/limit applies to a subset of locations under a policy, and 2) policy restrictions where only a subset of locations under the policy contribute loss.  There is no field which tells Oasis whether or not loss should be passed through for those locations without a CondNumber.

I propose the addition of a field in the Account file 
CondType tinyint (optional) with valid values (0 - sublimit) and (1 - policy restriction), and default value 0

The treatment of this field would be 
0 - Pass through losses of all locations and apply terms to locations with CondNumber
1 - Pass through losses of only locations with a CondNumber to the policy

There may be other types of special conditions that require different logic, in which case the list of valid values of CondType can be extended like it has been for other Type fields.

@MattDonovan82 for triage, @sambles @sstruzik @hchagani-oasislmf @benhayes21 fyi

This feature, or something along these lines, would be required for Oasis to properly support policy restrictions (target January 2021)

**Comment by johcarter** [comment]
Updated suggesting for field name **CondClass** as Type might be confused with DedType, LimitType 

So:
CondClass tinyint (optional) with valid values (0 - sublimit) and (1 - policy restriction), and default value 0

**Comment by johcarter** [comment]
Description: 'Class of Special Condition'

**Comment by MattDonovan82** [comment]
Added to data spec v1.1.3 in develop branch
