### ISSUE TITLE
New IFM OCC codes proposed by GC

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OpenDataStandards#23]
GC have proposed new occupancy codes to be used for more specific IFM occupancies - see attached.

In the notes, they suggest using a new specific codes within the current ranges - which makes sense.

Codes attached:

[OED_newcodes_20210107_GC.xlsx](https://github.com/OasisLMF/OpenDataStandards/files/5843429/OED_newcodes_20210107_GC.xlsx)

**Comment by benhayes21** [comment]
Conceptually it's OK - I think the key here is communication to users of the OED, particularly model providers who might have to make adjustments to their keys service logic to recognise and allow for the new codes.

**Comment by aiste-kalinauskaite** [comment]
I think it looks ok. You may want to double check that there are definitely no duplicates (I only had a quick glance). Additionally, I wasn't quite sure what the differentiation is between "2520 - Industrial Facilities Model, IFM: Nuclear Power Systems All- General" and their new proposed code for "2521 - Industrial Facilities Model, IFM: other Nuclear Facilities".
There were a couple other codes proposed to potentially add "General" code as well. It would be good to understand the difference between the two and then decide if it's needed.
From our side additional codes are ok - we just need to know which release they are coming in.

**Comment by delioma** [comment]
Thanks Aiste.  "2520 - Industrial Facilities Model, IFM: Nuclear Power Systems All- General" refers to generation of nuclear energy- mainly nuclear power plants. "2521 - Industrial Facilities Model, IFM: other Nuclear Facilities" are other facilities associated to the nuclear processes such as nuclear fuel fabrication, nuclear waste, nuclear medicine, nuclear weapons, nuclear machine building, nuclear plant engineering and construction, nuclear services and maintenance, nuclear R&D, military nuclear production, etc

**Comment by MattDonovan82** [comment]
all new IFM codes added in v1.1.5 - closed
