### ISSUE TITLE
Question about grouped perils in OED_Peril_Values.csv

### ISSUE THREAD

**Issue by chrisgundersen** [OasisLMF/OpenDataStandards#24]
Looking at the `OED_Peril_Values.csv` file here: `OpenExposureData/Schema/OED_Peril_Values.csv`

The examples show that given a peril code of `448`, the response would be the three wind codes (`WTC;WEC;WSS`). However, given a peril code of `16777215` it shows the response would be the "All perils" group code of `AA1`, since it has a specific peril code/description/abbreviation defined.

In that case why wouldn't `448` return "Windstorm with storm surge" with abbreviation `WW1`?

If the peril code exists as a specific row would we expect that data to be returned, or would we use the bitwise `AND` to return the list of individual peril codes?

**Comment by MattDonovan82** [comment]
Hi @chrisgundersen 
Can you please clarify what you mean? 

If you want to code rows of data in the input files for those three perils, you can use either "WW1" or WTC; WEC; WSS. 448 is the numerical code that is used in the SQL DB.  WW1 was introduced just to make its easier as group peril.

I'm not sure if this helps or not?

**Comment by benhayes21** [comment]
Closing issue

**Comment by chrisgundersen** [comment]
That helps - my question is more about what is expected. If one defined a "group peril", would the expectation be that you'd return the group peril code (`WW1`) given the decimal value of `448`, or would the expectation be that you'd return the list of individual peril codes (`WTC;WEC;WSS`)?

At the bottom of the doc it has a section titled "Examples of combining peril codes" it uses `448` as an example value returning `WTC;WEC;WSS`, even though there is a specific value set for `448` labeled "Windstorm with storm surge" that returns peril code `WW1`.

So if a "grouped" peril code value exists and is stored in the database (`WW1` for `448`), would the desired output be the one grouped peril code (`WW1`) or the individual peril codes (`WTC;WEC;WSS`)?
