### ISSUE TITLE
Update to codes for building rise

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OpenDataStandards#26]
Further to our earlier request on addition of some IFM-related codes, we would like to ask your opinion on the addition of some codes relating to building rise.
 
At present, OED has fields for the number of stories and for building height; however, for some territories/perils we are working on, client data is very coarse. Therefore, we would like implementing building rise descriptors for low, medium and high building rise.
 
Could that be a potential addition to OED, you think? If so, it would be great having your advice on suitable codes and descriptors. At our end, we are planning to implement this on Nasdaq using the flexifields option.
 
Look forward to your advice.
 
Thanks and best regards,
Delioma

**Comment by MattDonovan82** [comment]
Hi https://github.com/delioma

I'm opening this up to the wider group. As there are already a few fields in the loc for building height, I'm not sure we would want to continue adding fields for the same thing. I;m assuming you want this 'rise' field when you don't receive numstoreys?

**Comment by aiste-kalinauskaite** [comment]
I agree about not adding an additional field that serves the same purpose of the existing field. I would suggest adjusting BuildingHeight field for your model specific purpose. E.g. If you only have 3 categories: low / medium / high, why not to use 3 unique values in the BuildingHeight fied? E.g. 1 for low, 5 for medium and 10 for high. They can be changed in something more suitable if those particular values are not reasonable. Or have some ranges defined what would low / medium / high would mean in your model from using BuildingHeight field. I wouldn't advice adding Flexi field either, as the BuildingHeight is already there.

**Comment by delioma** [comment]
Hi Matt and Aiste, that makes sense, and we can define our own internal convention in terms of categories/ defined unique values. Thanks, Delioma

**Comment by MattDonovan82** [comment]
Issue closed
