### ISSUE TITLE
CondNumber question

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OpenDataStandards#30]
Should a CondNumber be able to have different terms by policy ?

Is the following data valid in OED account?

![image](https://user-images.githubusercontent.com/11421733/115007763-3e2d9f80-9ea2-11eb-98f5-f3cf9e5b2f22.png)

**Comment by aiste-kalinauskaite** [comment]
Short answer: no.
CondNumber should uniquely identify a special condition and as such all the terms should be the same for it.

**Comment by johcarter** [comment]
It seems as though the fm file generation code can handle this situation, based on the above use case

**Comment by johcarter** [comment]
These example cases contain different ways of expressing one set of special conditions (with single priority) when the condition terms vary by policy.

Case1 – Base case: 2 special conditions, 2 policies, the conditions are identical for each policy
Case2 – CondNumber uniquely describes terms: the condition terms on location 2 vary by policy. The variation is assigned a new CondNumber 3, leading to a duplicate entry in location file for location 2
Case3 – CondNumber uniquely describes location grouping but not terms: As for case 2 one of the conditions terms varies by policy, but both have the same CondNumber because they both apply to location 2. No need for duplicate entry in location file
Case4 – CondTag uniquely describes location grouping, CondNumber uniquely describes terms. (Re)introduce a field CondTag which uniquely identifies the location grouping for a condition, whereas CondNumber uniquely identifies the terms. Assign CondNumber to CondTag in the account file.

The problem with case 2 is that Oasis needs the location groupings to be consistent, while allowing for terms to vary by policy. Allowing duplicates in the location file leads to potentially unsupported groupings which makes the validation very hard.  It also makes the logic for grouping of locations very complicated and error prone, because which subset of condition numbers do you use ? 

Requiring only one row per location per priority as for case3 and case4 makes the validation much easier, because we can just look for duplicates which have equal priority. It makes the location grouping logic simple (currently its very complex). 

Note that Oasis currently supports case2 and case3 (pending fix for https://github.com/OasisLMF/OasisLMF/issues/813)

[cases_v2.zip](https://github.com/OasisLMF/OpenDataStandards/files/6386064/cases_v2.zip)

Questions:
1) Should we disallow case 2 and only allow one condition on each location for a given cond priority (illustrated in cases 3&4)? (Note that we can still allow multiple entries for hierachal conditions because we can use the CondPriority field to distinguish between conditions at different hierarchal levels)
2) If yes, should we introduce the new field CondTag into location and account to specify the scope of the condition, and keep the CondNumber in account file only to refer specifically to the financial terms? (is case4 preferred over case3?)
3) Are there any more condition scenarios that we need to consider - specifically any cases of multiple conditions on a location at the same priority?

**Comment by johcarter** [comment]
CondTag implemented in branch https://github.com/OasisLMF/OpenDataStandards/tree/feature/oed-schema-changes

**Comment by MattDonovan82** [comment]
added to release candidate for v2.0.0
