### ISSUE TITLE
OED file version field

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OpenDataStandards#33]
from feedback of the last ODS steering group meeting, it would be handy to know the OED schema version of a set of OED files. 

The version belongs in the meta data of the final data package long term, but in the short term and to help the tools that consume OED handle short term changes, the suggestion is to add it as an optional data field to each of the four OED input files.

I've added the field 'OEDVersion' in branch 
https://github.com/OasisLMF/OpenDataStandards/tree/feature/oed-schema-changes

**Comment by dsokol** [comment]
@johcarter Is it intended that the version number will be semantic?  It looks like it is, but wanted to confirm as that would be very helpful in doing ETL work, with a major rev breaking existing data imports and exports.

**Comment by johcarter** [comment]
hi @dsokol I was thinking just a string e.g. 2.0.0 to match the version in the OED spec. Is this what you meant? happy to hear any other suggestions.

**Comment by dsokol** [comment]
Works for me!  What I would hope is that that this number follows major.minor.patchwhere:

*major updates*:  breaking changes + massive new schema adds
*minor updates*: additive non-breaking changes
*patch*: minor updates / doc changes

This way we can export to and import from a major update version and build code around checking major and minor version number, being irrelevant to any sort of code.  https://semver.org/

**Comment by johcarter** [comment]
yes, this is exactly what I had in mind @dsokol . here are some examples with the other upcoming OED schema changes;
https://github.com/OasisLMF/OpenDataStandards/tree/feature/oed-schema-changes/OpenExposureData/Example_inputs/pi_wind

**Comment by MattDonovan82** [comment]
added to release candidate for v2.0.0
