### ISSUE TITLE
ORD report names: Change PALT to ALT

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OpenDataStandards#36]
In the ORD worked examples I refer to the Period Average Loss Table report as just Average Loss Table. There is only one variant of this report and so the P is superfluous. I suggest relabelling this report to just ALT. 

Unless there are objections on this thread or unless anyone thinks its worthy of discussion at the steering meeting, i'll make this change in the ODS v2 release candidate.

**Comment by MattDonovan82** [comment]
this makes sense Joh. I don't think it needs discussing at the SC.

**Comment by johcarter** [comment]
thanks @MattDonovan82 !

**Comment by MattDonovan82** [comment]
included in release candidate for  v2.0.0
