### ISSUE TITLE
Add new modifier StaticMotorVehicle in Location file

### ISSUE THREAD

**Issue by rtahiry** [OasisLMF/OpenDataStandards#4]
It would be helpful to have an new column 'StaticMotorVehicle' in the location file. This modifier primarily applies to motor vehicle exposures e.g. to differentiate a risk that is dynamic (e.g. moving from postcode to postcode for commute) and a risk that is static (e.g. a car yard or dealership store).

column name: StaticMotorVehicle
datatype: boolean (0 or 1)
meaning: 0 means the risk is a dynamic motor exposure, 1 means the risk is a static motor exposure
default value: 0

**Comment by aiste-kalinauskaite** [comment]
Please allow blank in this field (blanks to default to 0).
In SQL DB, this field would go into LocationDetails table.

**Comment by MattDonovan82** [comment]
is this merely an update to the input files to include this field?

**Comment by aiste-kalinauskaite** [comment]
This is an update to the input files and to SQL DB. The rest would be done by modellers, of they choose to use the field.

**Comment by MattDonovan82** [comment]
Hi Tahiry,
Apologies its been a while to respond to this - the ODS implementation/updates are still a work in progress.

We've had some discussion on this today and would an extra construction code for 'static motor vehicles/car dealership' suffice here? This would be the preferred option rather than creating a specific header in the loc file?

**Comment by MattDonovan82** [comment]
@rtahiry not sure if you saw this last comment?

**Comment by rtahiry** [comment]
Hi @MattDonovan82 ,

**Comment by MattDonovan82** [comment]
@benhayes21 It seems reasonable to include this field in OED. What do you think?

**Comment by MattDonovan82** [comment]
Added to data spec v1.1.3 in develop branch
