### ISSUE TITLE
Separated .csv's for OED Schema

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OpenDataStandards#41]
Does anyone think we need to keep all the tabs from the data spec .xlsx separate in the schemas folder as separate .csv's here?

https://github.com/OasisLMF/OpenDataStandards/tree/master/OpenExposureData/Schema

They are obviously all together in the data spec.xlsx. It's just more to maintain.

**Comment by aiste-kalinauskaite** [comment]
We use just xlsx.

**Comment by dsokol** [comment]
xlsx is _wide enough_ and has enough formatted benefits that it would be preferred here as well.

**Comment by MattDonovan82** [comment]
Removed the 'schema' directory in the 'develop' branch as separate .csv files are not required and means more maintaining. Will be merged to 'master' branch when v2.0.0 is released
