### ISSUE TITLE
More clarity to OED spec

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/OpenDataStandards#44]
Could you update the for fields (currently listed as 0 or 1 as datatype) to be tinyint? The fields were always intended to be 0 or 1 as an integer, but can be misinterpreted as boollean instead. Please update IsLimitAtDamage, IsPrimary, IsTenant and StaticMotorVehicle:
![image](https://user-images.githubusercontent.com/42062835/130427907-67a89e0e-df8f-4782-9be8-eae8f46e640d.png)

Adding ValidRange [0,1] will give even more clarity what the fields are.
Please add it in the next release.

**Comment by MattDonovan82** [comment]
Updates made in the 'develop' branch - will be merged to 'master' with the release of v2.0.0
