### ISSUE TITLE
Adding Fields for Aggregate Data in OED

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OpenDataStandards#45]
As there are clearly use cases for aggregate data in OED (Combus, PERILS) etc, would it be beneficial to add some permanant fields that can accommodate aggregate data rather than relying on Flexi fields/user def fields? A 'number of risks' field for example would be useful as its different to 'Number of buildings' which is used for a campus location. 

Was there any specific reason that aggregate data fields were not implemented in OED from the start?

**Comment by johcarter** [comment]
In particular any other fields needed for disaggregation of TIVs and financial terms, so that aggregate exposure data can be run in a detailed loss model?

**Comment by MattDonovan82** [comment]
As discussed in a call a few weeks ago, an aggregate field for a flag added to the loc file was suggested as the best way forward for this. 
Suggestions for data field and type:

'AggData' for field name
Text or int for value? 'Yes/No' or '0/1' ?

**Comment by aiste-kalinauskaite** [comment]
I would suggest going for 0/1 - there are other fields in OED which describe "yes/no" type scenarios and I believe they are all described as 0/1. (e.g. IsTenant, IsPrimary).

**Comment by MattDonovan82** [comment]
thanks @aiste-kalinauskaite. we will include this into v2 unless there are any other comments?

**Comment by johcarter** [comment]
How about 'IsAggregate' (0/1) for consistancy with other binary fields?

**Comment by aiste-kalinauskaite** [comment]
Good suggestion Joh. Ok to get it into v2 from my perspective.

**Comment by MattDonovan82** [comment]
yep, makes sense.

**Comment by MattDonovan82** [comment]
closed as included in ODS v2.0.0
