### ISSUE TITLE
Request from JBA to add more geogschemes 

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OpenDataStandards#51]
JBA would like to have more than the existing 5 Geoschemes added to the OED schema to help with their validation issues.

They would also like ISO3A added as a geogscheme.

I would suggest maybe adding another 5 geogschemes but I;ll check if this is sufficient for them.

Anyone have any issues with this?

**Comment by johcarter** [comment]
no issues

**Comment by jones-matt** [comment]
I can only see one JBA GeogScheme in the OED spreadsheet currently. So to clarify, are we talking about adding 'JBA2', 'JBA3'.. 'JBA6' plus 'ISO3' as new permitted values in the GeogScheme fields?

**Comment by JBADougBurns** [comment]
Yep, new GeogScheme / GeogName pairs please. (I think we have additional JBA* GeogSchemes already, but I may be misremembering that one.)

**Comment by JBADougBurns** [comment]
I guess flexi fields could have on impact on validation performed by, say, NRMC? I would be hesitant to break any external handling at the moment. For us internally there is no issue. (We would be interested in flexi GeogScheme fields going forwards though)

It sounds like the best solution now is to add the additional fields.

**Comment by JBADougBurns** [comment]
Thanks for the update @MattDonovan82. Sounds great to me!

**Comment by MattDonovan82** [comment]
closed as included in ODS v2.0.0
