### ISSUE TITLE
Add new value 4 to PayoutType for step policies

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OpenDataStandards#53]
We realised we needed a new value for PayoutType for a calcrule which would payout 'conditional coverages' only for step policies, rather than adding the conditional coverage to the primary coverage.  

The conditional coverages in step policies are extra expenses which are calculated as a proportion of the primary coverage payout, and may have a limit, and debris removal which is applied as a scaling factor to the sum of the primary coverage and the extra expense payouts.
 Because these conditional coverages are not calculated independently and depend on the primary coverage, they must be added to the primary coverage payout (being structure, or contents, or structure+contents) via the step policy calcrules.

In some complex policy types, the trigger level for the extra expenses loss is different to the primary coverage payout. This is dealt with in Oasis by creating a second step to generate the conditional coverage payout, which is based on the first step paying out (the primary coverage payout). In this way we can support different trigger levels for the primary coverage and the conditional coverage.

A description for this would be ;
PayOutType=4 
Conditional coverages only, based on prior step payout
Please can we add this to OED spec (Financial Code Values tab and csv) @MattDonovan82 ?

NB - ready for release in Oasis!
https://github.com/OasisLMF/ktools/pull/246
https://github.com/OasisLMF/OasisLMF/issues/927

**Comment by aiste-kalinauskaite** [comment]
Is this going to OED v2?

**Comment by johcarter** [comment]
No, v2 has just been released to master. This can go into the next minor update.

**Comment by MattDonovan82** [comment]
@aiste-kalinauskaite there will probably be a v2.1.0 before the end of the year

**Comment by MattDonovan82** [comment]
@johcarter I will add these to the data spec.

**Comment by MattDonovan82** [comment]
included in v2.1
