### ISSUE TITLE
Adding occupancy codes for motor to OED

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OpenDataStandards#55]
There have now been a couple of requests for motor/automobiles in OED in addition to the automobile manufacturing or parking that is already supported.

Would need to cover:

* Residential auto
* Commercial auto/fleet

any others? There may be a couple of models in Oasis that already support motor so it would be beneficial to see how they code it in OED - maybe just a flexi field?

**Comment by aiste-kalinauskaite** [comment]
I think we have a very extensive selection of coding a variation of automobiles:

![image](https://user-images.githubusercontent.com/42062835/140912557-f6096d35-88f3-48a0-8a42-e085978d9f7f.png)

**Comment by MattDonovan82** [comment]
thanks @aiste-kalinauskaite I was focussing on the occupancy rather than the construction, so apologies. This should be fine for this.
