### ISSUE TITLE
Adding new occupancy and construction classes to OED

### ISSUE THREAD

**Issue by unnithan9** [OasisLMF/OpenDataStandards#58]
Hi,
We would like to suggest some of the occupancy and construction class that are missing in OED. Please find attached the pdf having some of the missing occupancy and construction classes . It would be great if you can review the proposed OED codes and suggest some for the missing class.
[OED Class.pdf](https://github.com/OasisLMF/OpenDataStandards/files/7703472/OED.Class.pdf)
Thanks 
Vipin

**Comment by MattDonovan82** [comment]
Hi @unnithan9 
In general these suggestions looks reasonable but I do have a few questions/suggestions below just so we are definitely not duplicating codes/descriptions.

Occupancy:

* Can you please clarify the main difference between your proposed code 1057 vs the current 1055? What do you mean by the term "renter"?
* So the difference between your proposed code of 1058 vs the current 1055 is to cover the communal areas within a code or apartment building? If so, can you add a few examples within the description as to what it covers, i.e. stairwells, lobby etc?

Construction:

* I'm not quite sure the difference between your purposed 'wind resistive' and 'very wind resistive' compared to the current 'Special, semi-wind resistive' and 'Special, wind resistive'. I understand the descriptions are different but it sounds like they are covering similar things. 

I suggest if your proposed codes are to cover buildings that are of a 'higher performance' to wind, I would name them as such and in the description mention why they are different to the proposed codes/descriptions? For example, yours could be called:

*  'Special, high performance, wind resistive' - proposed code 5307
*  'Special, high performance, very wind resistive' - proposed code 5308

* Proposed code for your 'Flood Resistance General' could be 5309

In general, we just need to differentiate with existing codes. All the other proposed codes look fine.

Matt

**Comment by MattDonovan82** [comment]
Thanks. A more detailed description of the proposals will be appreciated.

It seems these 'high performance' codes should be grouped together so a slight amendment might be

* 'Basement Loss, Sensitive' - proposed code 5309 - suggest the name should be more like 'Basement Flood Loss, High Value' or something similar?
* 'Flood Resistance General' proposed code 5310

**Comment by MattDonovan82** [comment]
As discussed offline, until these codes are released into the schema as a version update (will be v2.1.0), the use of these new codes cannot be deployed externally and should only be used for your own internal model testing/usage. If so, it would cause validation processes to fail as these new codes would not be present in previous versions of OED.

**Comment by unnithan9** [comment]
Yes we will be providing a detailed description for the proposed codes, and I do understand that this can be used for internal model testing/usage until this makes into the schema as a version update. Thank you Matt for the support!

-Vipin

**Comment by MattDonovan82** [comment]
@unnithan9 Please add the detail descriptions and all details of what will be included in the schema to this Issue (can be another attachment if thats easier), to keep it all together and open for others to comment. thanks.

**Comment by unnithan9** [comment]
Hi Matt,

Please find attached the pdf which includes the proposed codes, names and a detailed description of each class. Please let me know if you need any additional information
[OED.pdf](https://github.com/OasisLMF/OpenDataStandards/files/7739469/OED.pdf)

Thanks for the support.

-Vipin

**Comment by MattDonovan82** [comment]
@unnithan9 please review the additions you proposed in the data spec.xlsx of the develop brach below. They will be included in the v2.1 release in the next week. Thanks.
https://github.com/OasisLMF/OpenDataStandards/tree/develop/OpenExposureData/Docs

**Comment by unnithan9** [comment]
Hi @MattDonovan82 
I have reviewed the proposed additions in the xls file, and it looks fine. Thank you for the support.

-Vipin

**Comment by MattDonovan82** [comment]
include in v2.1
