### ISSUE TITLE
Add valid range for StepNumber

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/OpenDataStandards#6]
I have missed this, but it is defined in description. Please add [1,10] for valid range (column H) for StepNumber in 'OED Input Fields' tab.

**Comment by MattDonovan82** [comment]
This looks like  a simple addition to the data spec.xlsx.
It will be actioned once the process for doc versioning has been confirmed.

**Comment by MattDonovan82** [comment]
done and will be included in next release

**Comment by MattDonovan82** [comment]
will leave open until next release
