### ISSUE TITLE
Split or define XX fields

### ISSUE THREAD

**Issue by johanxnilsson** [OasisLMF/OpenDataStandards#65]
Hi!

OED v2 has two fields (GeogNameXX and GeogSchemeXX) marked with XX as suffix with an explanation in the description what it means. This does however break the ability for automatic imports of the rules since the field name is no longer the actual name. Would it be possible to revert this back to have it in the same way as v1 with all fields specified (but 1-20 instead of 1-5)?

If this is not desirable - would it be possible to define what XX means? Either by specifying XX always means 1-20, or wildcard match (match anything) or with one additional column to set supported ranges or a regexp for pattern matching?

This would make it more clear and also support automatic imports.

**Comment by MattDonovan82** [comment]
Hi Johan,

This was only updated to accommodate extra geogschemes and not be limited to just 5 so we can define it as always means 1-20 if that works for you? We decided using the 'XX' avoids the need for multiple columns for each explicit geoscheme/name.

I can update the description to state it can accommodate upto 20 as explained?

**Comment by johanxnilsson** [comment]
Hello!
That would work for us, but to make it generic the same rules should be applied to all future XX fields in that case. Would that work? If new XX fields are added in the future, will it be enough to use the same rules for them and accept only 1-20 as a suffix?

**Comment by MattDonovan82** [comment]
I'm quite sure this would work but I'll have to check 20 will be enough for other fields - can this be made 30 for example to cover all cases?

**Comment by johanxnilsson** [comment]
Sure, any number (or character for that matter) will be fine by us as long as all XX suffix means the same thing for all fields using it.

**Comment by aiste-kalinauskaite** [comment]
I don't think that there are any other XX fields currently in the spec, but I will leave @MattDonovan82  to check.

**Comment by MattDonovan82** [comment]
no there isn't so lets make the 'xx' 1-30 which will be more than enough for geogname/scheme @johanxnilsson

**Comment by johanxnilsson** [comment]
Alright, thanks!

**Comment by MattDonovan82** [comment]
closed as implemented into the wording in v2.2.0
